use_frameworks!

target 'AJLabelAppearance_Example' do
  pod 'AJLabelAppearance', :path => '../'

  target 'AJLabelAppearance_Tests' do
    inherit! :search_paths
    pod 'AJLabelAppearance', :path => '../'
  end
end
