use_frameworks!

target 'AJLabelAppearance_Example' do
  pod 'AJLabelAppearance', :git => 'https://github.com/ajabble/LabelAppearance.git'

  target 'AJLabelAppearance_Tests' do
    inherit! :search_paths
    pod 'AJLabelAppearance', :git => 'https://github.com/ajabble/LabelAppearance.git'
  end
end
